name: 'Cactus'
description: 'Cactus Release Manager'
inputs:
  token:
    description: 'User based token with write permission'
    required: true
  next_version:
    description: 'Version of the next release'
    required: true
  project:
    description: 'Project to cut'
    required: true
  labels:
    description: 'List of labels to add to release candidate'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
