name: Test
on: [pull_request]

jobs:
  changelog:
    name: Changelog
    if: contains(github.head_ref, 'dependabot') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zattoo/changelog@v1
        with:
          token: ${{github.token}}
